name: schedular
on:
  schedule:
    - cron: "*/5 * * * *"
    - cron: "*/6 * * * *"
jobs:
  execute-task:
    runs-on: ubuntu-latest
    steps:
      - name: list files
        run: |
          ls 
          pwd
